import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "../../globals.css";

const lexend = Lexend_Deca({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SignInLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className={`relative min-h-screen ${lexend.className}`}>
      {/* Background image */}
      <div
        className="absolute inset-0 bg-cover bg-center"
        style={{ backgroundImage: "url('/bg-image.png')" }}
      />

      {/* Dark overlay */}
      <div className="absolute inset-0 bg-black/60" />

      {/* Page content */}
      <div className="relative z-10">{children}</div>
    </main>
  );
}

export default SignInLayout;
